# Generated by Django 2.2.10 on 2020-03-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('address', models.TextField(blank=True)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
