# Generated by Django 2.2.11 on 2020-03-21 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Test'),
        ),
    ]
